import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

import sv from 'semver'
import { afterEach, describe, expect, it, vi } from 'vitest'

import { format, getLockfileType, parse, patch } from '../../main/ts/lockfile'
import { patchLockfile } from '../../main/ts/stages'

// Spy the audit stage so the flow stays offline; correctness of the audit itself
// lives in audit-registry.ts. `_internal._audit` is what `lf.audit` delegates to.
const lf = (await import('../../main/ts/lockfile'))._internal
const audit = vi.spyOn(lf, '_audit')

// Offline canned registry: lodash 4.17.11 (vuln) → 4.18.0 (fix), no deps.
const registry = {
  packument: async (name: string) =>
    name === 'lodash'
      ? {
          name,
          distTags: { latest: '4.18.0' },
          versions: {
            '4.17.11': { name, version: '4.17.11', dependencies: {} },
            '4.18.0': { name, version: '4.18.0', dependencies: {} },
          },
        }
      : undefined,
  resolve: async (name: string, range: string) => {
    if (name !== 'lodash') return undefined
    const v = ['4.18.0', '4.17.11'].find((x) => sv.satisfies(x, range))
    return v ? { name, version: v, dependencies: {} } : undefined
  },
} as any

const report = {
  lodash: {
    module_name: 'lodash', // eslint-disable-line camelcase
    vulnerable_versions: '<4.18.0', // eslint-disable-line camelcase
    patched_versions: '>=4.18.0', // eslint-disable-line camelcase
  },
}

// A realistic yarn-classic lock with lodash resolved to the vulnerable 4.17.11
// (the entry key is the declared descriptor — exact or ranged).
const lock = (key: string): string =>
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n' +
  '# yarn lockfile v1\n\n\n' +
  `${key}:\n` +
  '  version "4.17.11"\n' +
  '  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.11.tgz#b39ea6229ef607ecd89e2c8df12536891cac9b8d"\n' +
  '  integrity sha512-cQKh8igo5QUhZ7lg38DYWAxMvjSAKG0A8wGSVimP07SIUEK2UO+arSRKbRZWtelMtN5V0Hkwh5ryOto/SshYIg==\n'

// A throwaway project dir with package.json + yarn.lock; returns cwd + the yaf ctx.
const project = (pkgRange: string, lockKey: string, flags: Record<string, any>) => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'yaf-mg-'))
  const manifest = { name: 'proj', private: true, dependencies: { lodash: pkgRange } }
  fs.writeFileSync(path.join(cwd, 'package.json'), JSON.stringify(manifest, null, 2) + '\n')
  fs.writeFileSync(path.join(cwd, 'yarn.lock'), lock(lockKey))
  const context: any = { cwd, flags: { silent: true, ...flags }, manifest, registry }
  context.ctx = context // TContext self-reference (patchLockfile destructures { ctx })
  return { cwd, context }
}

const pkgRange = (cwd: string): string =>
  JSON.parse(fs.readFileSync(path.join(cwd, 'package.json'), 'utf-8')).dependencies.lodash
const readLock = (cwd: string): string => fs.readFileSync(path.join(cwd, 'yarn.lock'), 'utf-8')

describe('manifest gate — integration (patchLockfile on a real project dir)', () => {
  afterEach(() => {
    audit.mockReset()
  })

  it('default: leaves package.json + yarn.lock untouched, dep stays vulnerable', async () => {
    audit.mockResolvedValue(report)
    const { cwd, context } = project('4.17.11', 'lodash@4.17.11', {})
    await patchLockfile(context)
    expect(pkgRange(cwd)).toBe('4.17.11') // untouched
    expect(readLock(cwd)).toContain('version "4.17.11"') // not bumped
  })

  it('--force: rewrites the package.json range + bumps the lock in place', async () => {
    audit.mockResolvedValue(report)
    const { cwd, context } = project('4.17.11', 'lodash@4.17.11', { force: true })
    await patchLockfile(context)
    expect(pkgRange(cwd)).toBe('4.18.0') // rewritten (exact style preserved)
    const l = readLock(cwd)
    expect(l).toContain('lodash@4.18.0:') // key reset (exact pin can't hold the old descriptor)
    expect(l).toContain('version "4.18.0"') // bumped
  })

  it('--dry-run --force: computes the edit but writes NOTHING', async () => {
    audit.mockResolvedValue(report)
    const { cwd, context } = project('4.17.11', 'lodash@4.17.11', { force: true, 'dry-run': true })
    await patchLockfile(context)
    expect(pkgRange(cwd)).toBe('4.17.11') // untouched (dry-run)
    expect(readLock(cwd)).toContain('version "4.17.11"') // untouched
  })

  it('caret admitting the fix: bumps the lock, leaves package.json alone', async () => {
    audit.mockResolvedValue(report)
    const { cwd, context } = project('^4.17.0', 'lodash@^4.17.0', {})
    await patchLockfile(context)
    expect(pkgRange(cwd)).toBe('^4.17.0') // untouched (still admits 4.18.0)
    const l = readLock(cwd)
    expect(l).toContain('lodash@^4.17.0:') // descriptor preserved
    expect(l).toContain('version "4.18.0"') // bumped
  })

  it('scoped exact pin under --force: rewrites the range, scoped path minted', async () => {
    audit.mockReset()
    audit.mockResolvedValue({
      '@scope/x': {
        module_name: '@scope/x', // eslint-disable-line camelcase
        vulnerable_versions: '<2.0.0', // eslint-disable-line camelcase
        patched_versions: '>=2.0.0', // eslint-disable-line camelcase
      },
    })
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'yaf-mg-'))
    const manifest = { name: 'proj', private: true, dependencies: { '@scope/x': '1.0.0' } }
    fs.writeFileSync(path.join(cwd, 'package.json'), JSON.stringify(manifest, null, 2) + '\n')
    fs.writeFileSync(
      path.join(cwd, 'yarn.lock'),
      '# yarn lockfile v1\n\n\n"@scope/x@1.0.0":\n  version "1.0.0"\n' +
        '  resolved "https://registry.yarnpkg.com/@scope/x/-/x-1.0.0.tgz#' +
        '0000000000000000000000000000000000000000"\n  integrity sha512-AA==\n',
    )
    const scopedRegistry = {
      packument: async (name: string) =>
        name === '@scope/x'
          ? { name, distTags: { latest: '2.0.0' }, versions: { '1.0.0': { name, version: '1.0.0', dependencies: {} }, '2.0.0': { name, version: '2.0.0', dependencies: {} } } }
          : undefined,
      resolve: async (name: string, range: string) =>
        name === '@scope/x' && sv.satisfies('2.0.0', range)
          ? { name, version: '2.0.0', dependencies: {} }
          : undefined,
    } as any
    const context: any = { cwd, flags: { silent: true, force: true }, manifest, registry: scopedRegistry }
    context.ctx = context
    await patchLockfile(context)
    expect(JSON.parse(fs.readFileSync(path.join(cwd, 'package.json'), 'utf-8')).dependencies['@scope/x']).toBe('2.0.0')
    expect(readLock(cwd)).toContain('"@scope/x@2.0.0":')
  })

  // Cross-format proof: the gate is manifest-based, so it fires the same for berry.
  // Patch level (not patchLockfile) so berry's checksum refurbish never hits the net.
  it('cross-format: trips + records the rewrite for a yarn-berry-v8 lock', async () => {
    const berryLock =
      '# This file is generated by running "yarn install" inside your project.\n' +
      '# Manual changes might be lost - proceed with caution!\n\n' +
      '__metadata:\n  version: 8\n  cacheKey: 10c0\n\n' +
      '"lodash@npm:4.17.11":\n  version: 4.17.11\n  resolution: "lodash@npm:4.17.11"\n' +
      `  checksum: 10c0/${'a'.repeat(128)}\n  languageName: node\n  linkType: hard\n\n` +
      '"proj@workspace:.":\n  version: 0.0.0-use.local\n  resolution: "proj@workspace:."\n' +
      '  dependencies:\n    lodash: "npm:4.17.11"\n  languageName: unknown\n  linkType: soft\n'
    const fmt = getLockfileType(berryLock)
    expect(fmt).toBe('yarn-berry-v8')
    const context: any = {
      flags: { silent: true, force: true },
      manifest: { dependencies: { lodash: '4.17.11' } },
      registry,
      cwd: process.cwd(),
    }
    context.ctx = context
    const out = format(await patch(parse(berryLock, fmt), report, context, fmt), fmt)
    expect(context.manifestEdits).toEqual([
      expect.objectContaining({ name: 'lodash', from: '4.17.11', to: '4.18.0' }),
    ])
    expect(out).toContain('lodash@npm:4.18.0') // bumped resolution in the berry lock
  })

  // Monorepo: the pin lives in a WORKSPACE package.json, not the root. The gate
  // must find it (root `workspaces` → glob) and rewrite that file, not the root.
  const monorepo = (flags: Record<string, any>) => {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'yaf-ws-'))
    const root = { name: 'root', private: true, workspaces: ['packages/*'] }
    fs.writeFileSync(path.join(cwd, 'package.json'), JSON.stringify(root, null, 2) + '\n')
    const wsDir = path.join(cwd, 'packages', 'foo')
    fs.mkdirSync(wsDir, { recursive: true })
    fs.writeFileSync(
      path.join(wsDir, 'package.json'),
      JSON.stringify({ name: 'foo', dependencies: { lodash: '4.17.11' } }, null, 2) + '\n',
    )
    fs.writeFileSync(path.join(cwd, 'yarn.lock'), lock('lodash@4.17.11'))
    const context: any = { cwd, flags: { silent: true, ...flags }, manifest: root, registry }
    context.ctx = context
    const wsRange = () =>
      JSON.parse(fs.readFileSync(path.join(wsDir, 'package.json'), 'utf-8')).dependencies.lodash
    return { cwd, wsDir, context, wsRange }
  }

  it('monorepo default: a workspace pin the fix falls outside is flagged, not bumped', async () => {
    audit.mockResolvedValue(report)
    const { cwd, context, wsRange } = monorepo({})
    await patchLockfile(context)
    expect(wsRange()).toBe('4.17.11') // workspace pin untouched
    expect(readLock(cwd)).toContain('version "4.17.11"') // lock not bumped
  })

  it('monorepo --force: rewrites the WORKSPACE package.json (not the root) + bumps', async () => {
    audit.mockResolvedValue(report)
    const { cwd, context, wsRange } = monorepo({ force: true })
    await patchLockfile(context)
    expect(wsRange()).toBe('4.18.0') // the workspace's pin was rewritten
    // root package.json is untouched (it never declared lodash)
    expect(JSON.parse(fs.readFileSync(path.join(cwd, 'package.json'), 'utf-8'))).not.toHaveProperty(
      'dependencies',
    )
    expect(readLock(cwd)).toContain('lodash@4.18.0:') // bumped in the lock
  })
})
